[docs] replaced sphinx-bootstrap-theme with sphinx-rtd-theme
PhiLFitters/kafe2 pull request #242
Opened 2023-12-04 16:17 UTC by MitchiLaser

This pull request contains many commits which replace the sphinx-bootstrap-theme with the sphinx-rtd-theme. Furthermore a lot of files which were located in the configuration directory for Sphinx were removed because they were never needed.

Please squash all the commits when accepting the pull request, they are still separated in case a wrong file was deleted.

2023-12-04 16:21 UTC, MitchiLaser commented
Fixes #158

2023-12-06 12:56 UTC, cverstege requested changes
Looks good. Only two minor comments inline.

2023-12-06 12:56 UTC, cverstege commented on doc/src/conf.py
> +authors = ", ".join([i['name'].split(' ')[0][0] + ". " + i['name'].split(' ')[1] for i in pyproject['authors']])
You might want to use the last part as last name. E.g. if there are multiple first names
```suggestion
authors = ", ".join([i['name'].split(' ')[0][0] + ". " + i['name'].split(' ')[-1] for i in pyproject['authors']])
```

2023-12-06 12:56 UTC, cverstege commented on pyproject.toml
>  ]
Maybe add a comment about alphabetical ordering.

2023-12-06 16:10 UTC, MitchiLaser commented on pyproject.toml
>  ]
I added a comment above the list of authors

2023-12-06 16:11 UTC, MitchiLaser commented on doc/src/conf.py
> +authors = ", ".join([i['name'].split(' ')[0][0] + ". " + i['name'].split(' ')[1] for i in pyproject['authors']])
Done. This line might still not work perfectly for every case but it is getting the job done for the current list of maintainers.

2023-12-07 13:49 UTC, JohannesGaessler approved these changes

2023-12-07 13:49 UTC, JohannesGaessler commented on doc/src/conf.py
> +# the '_templates' directory was existing in the past but the template in there wasn't used at all.
```suggestion
# the '_templates' directory exited in the past but the template in there wasn't used at all.
```

2023-12-07 13:49 UTC, JohannesGaessler commented on pyproject.toml
> +# the list of authors is ordered alphabetically by the last name
```suggestion
# the list of authors is ordered alphabetically by last name
```

2023-12-07 13:53 UTC, merged